version: '3'

services: 
  api-solid-pg:
    image: bitnami/postgresql
    ports: 
      - 5433:5432
    enviroment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid